### ISSUE TITLE
Typeography

### ISSUE THREAD

**Issue by alexespejo** [alexespejo/booksmart#7]
We want the font and format of the web app to be as uniform as possible. As far as Typography is concerned we want to establish some default stylings that will apply throughout the website. 

1. Navigate to the [global.css file](https://github.com/alexespejo/booksmart/blob/main/assets/css/global.css).
2. Open up the [Figma](https://www.figma.com/file/4joGy9ijlU8CBqXxh0gdkB/Booksmart?type=design&node-id=0%3A1&mode=design&t=4huP4Bg1UDofhlJh-1) file and take a look at the style guide where you'll see a list of Typography content for the heading elements (i.e. h1, h2, h3, etc.) and give those elements css stylings. 

Example: 
```css
h1, h2, h3, h4, h5, h6 {
   margin: 0;
   padding: 0;
}

h1 {
//fill in css styling
}
h2 {
//fill in css styling
}
//continue
```
